seed_everything: 42

data:
  class_path: "src.data.DataModule"
  init_args:
    train_chip_dir: "/home/taylor/data/MP-RGB-Jul2025-224/train"
    val_chip_dir: "/home/taylor/data/MP-RGB-Jul2025-224-full/val"
    test_chip_dir: "/home/taylor/data/MP-RGB-Jul2025-224-full/test"
    batch_size: 128
    fill_value: 0
    fill_mask: 0
    num_workers: 8
    pin_memory: true
    persistent_workers: true

model:
  class_path: "src.models.smp.SMPSegmentationModel"
  init_args:
    architecture: "Segformer"
    backbone: "mit_b3"
    model_opts:
      encoder_weights: imagenet
      in_channels: 3
    num_classes: 1
    ignore_index: &ignore_index -100
    lr: 3e-4
    wd: 0.01
    b1: 0.9
    b2: 0.95
    loss: "LovaszLoss"
    loss_opts:
      mode: "binary"
      ignore_index: *ignore_index
      from_logits: true

trainer:
  accelerator: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  log_every_n_steps: 5
  max_epochs: 20
  accumulate_grad_batches: 2
  gradient_clip_val: 0.5
  detect_anomaly: false
  default_root_dir: checkpoints
  fast_dev_run: False
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: hakai
        project: kom-mussels-rgb
        name: segformer_b3
        group: Jul2025
        log_model: true
        tags:
          - mussels
          - Jul2025
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        auto_insert_metric_name: False
        filename: mussels_rgb_segformer_b3_epoch-{epoch:02d}_val-iou-{val/iou_epoch:.4f}
        monitor: val/iou_epoch
        mode: max
        save_last: True
        save_top_k: 2
        save_weights_only: True
        verbose: True
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
