seed_everything: 0

data:
  train_chip_dir: "/home/taylor/data/MP-RGB-May2024-1024-1024/train"
  val_chip_dir: "/home/taylor/data/MP-RGB-May2024-1024-1024/val"
  test_chip_dir: "/home/taylor/data/MP-RGB-May2024-1024-1024/test"
  batch_size: 3
  fill_value: 0
  fill_mask: 0
  num_workers: 8
  pin_memory: true
  persistent_workers: true

model:
  architecture: "Segformer"
  backbone: "mit_b3"
  model_opts:
    encoder_weights: imagenet
    in_channels: 3
  num_classes: 1
  ignore_index: &ignore_index 2
  lr: 3e-4
  wd: 0.01
  b1: 0.9
  b2: 0.95
  loss: "LovaszLoss"
  loss_opts:
    mode: "binary"
    from_logits: true
    ignore_index: *ignore_index

trainer:
  accelerator: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  log_every_n_steps: 5
  max_epochs: 20
  accumulate_grad_batches: 8
  gradient_clip_val: 0.5
  default_root_dir: checkpoints/kom-mussels-rgb
  fast_dev_run: False
  num_sanity_val_steps: 0
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: hakai
        project: kom-mussels-rgb
        name: segformer-b3
        group: May2024
        log_model: true
        tags:
          - mussels
          - May2024
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/kom-mussels-rgb
        auto_insert_metric_name: False
        filename: mussels_segformer_b3_epoch-{epoch:02d}_val-iou-{val/iou:.4f}
        monitor: val/iou
        mode: max
        save_last: True
        save_top_k: 2
        save_weights_only: True
        verbose: True
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
