version: "3.9"

# Default config to use all GPUs
x-deploy: &default-deploy
  replicas: 1
  resources:
    limits:
      memory: 8G
    reservations:
      memory: 2G
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  s3vol:
    image: elementar/s3-volume
    command: /data s3a://${BUCKET_NAME}
    env_file:
      - ".env"
    volumes:
      - s3data:/data

  tensorboard:
    image: tensorflow/tensorflow:2.4.3
    env_file: ".env"
    ports:
      - "0.0.0.0:6006:6006"
    command: [
        "tensorboard",
        "--logdir=s3://hakai-deep-learning-datasets/checkpoints/",
        "--host=0.0.0.0",
        "--port=6006"
    ]

  mussels-train-lraspp-mobilenetv3:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    depends_on:
      - s3vol
    volumes:
      - "s3data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
          "python",
          "lit_lraspp_mobilenet_v3_large.py",
          "train",
          "/data/mussels",
          "s3a://hakai-deep-learning-datasets/checkpoints",
          "--name=lr_aspp_mussels",
          "--num_classes=2",
          "--lr=0.0003",
          "--weight_decay=0.001",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--strategy=ddp",
          "--gpus=-1",
          "--benchmark",
          "--sync_batchnorm",
          "--max_epochs=100",
          "--batch_size=8",
          "--precision=16",
          "--log_every_n_steps=10",
      ]

  mussels-train-deeplabv3-resnet101:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    depends_on:
      - s3vol
    volumes:
      - "s3data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
          "python",
          "lit_deeplabv3_resnet101.py",
          "train",
          "/data/mussels",
          "s3a://hakai-deep-learning-datasets/checkpoints",
          "--name=deeplab_mussels",
          "--num_classes=2",
          "--lr=0.001",
          "--backbone_lr=0.0001",
          "--weight_decay=0.001",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--strategy=ddp",
          "--gpus=-1",
          "--benchmark",
          "--sync_batchnorm",
          "--max_epochs=100",
          "--batch_size=8",
          "--precision=16",
          "--log_every_n_steps=10",
      ]

  kelp-pa-train-lraspp-mobilenetv3:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    depends_on:
      - s3vol
    volumes:
      - "s3data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
          "python",
          "lit_lraspp_mobilenet_v3_large.py",
          "train",
          "/data/kelp/May2020",
          "s3a://hakai-deep-learning-datasets/checkpoints",
          "--name=lr_aspp_kelp_pa",
          "--num_classes=2",
          "--lr=0.001",
          "--weight_decay=0.001",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--strategy=ddp",
          "--gpus=-1",
          "--benchmark",
          "--sync_batchnorm",
          "--max_epochs=100",
          "--batch_size=8",
          "--precision=16",
          "--log_every_n_steps=10",
      ]

  kelp-pa-train-deeplabv3-resnet101:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    depends_on:
      - s3vol
    volumes:
      - "s3data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
          "python",
          "lit_deeplabv3_resnet101.py",
          "train",
          "/data/kelp/May2020",
          "s3a://hakai-deep-learning-datasets/checkpoints",
          "--name=deeplab_kelp_pa",
          "--num_classes=2",
          "--lr=0.001",
          "--backbone_lr=0.0001",
          "--weight_decay=0.001",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--strategy=ddp",
          "--gpus=-1",
          "--benchmark",
          "--sync_batchnorm",
          "--max_epochs=100",
          "--batch_size=8",
          "--precision=16",
          "--log_every_n_steps=10",
      ]

  kelp-species-train-lraspp-mobilenetv3:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    depends_on:
      - s3vol
    volumes:
      - "s3data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
          "python",
          "lit_lraspp_mobilenet_v3_large.py",
          "train",
          "/data/kelp_species",
          "s3a://hakai-deep-learning-datasets/checkpoints",
          "--name=lr_aspp_kelp_species",
          "--num_classes=3",
          "--ignore_index=1",
          "--lr=0.0005",
          "--weight_decay=0.001",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--strategy=ddp",
          "--gpus=-1",
          "--benchmark",
          "--sync_batchnorm",
          "--max_epochs=100",
          "--batch_size=8",
          "--precision=16",
          "--log_every_n_steps=10",
      ]

  kelp-species-train-deeplabv3-resnet101:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    depends_on:
      - s3vol
    volumes:
      - "s3data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
          "python",
          "lit_deeplabv3_resnet101.py",
          "train",
          "/data/kelp_species",
          "s3a://hakai-deep-learning-datasets/checkpoints",
          "--name=deeplab_kelp_species",
          "--num_classes=3",
          "--ignore_index=1",
          "--lr=0.001",
          "--backbone_lr=0.0001",
          "--weight_decay=0.001",
          "--gradient_clip_val=0.5",
          "--pa_weights=/data/best-val_miou=0.9393-epoch=97-step=34789.pt",
          "--accelerator=gpu",
          "--strategy=ddp",
          "--gpus=-1",
          "--benchmark",
          "--sync_batchnorm",
          "--max_epochs=100",
          "--batch_size=8",
          "--precision=16",
          "--log_every_n_steps=10",
      ]

volumes:
  torch_cache:
  s3data:
    driver: local
