version: "3.9"

services:
  mussels-train-lraspp-mobilenetv3:
    command:
      [
          "python",
          "lit_lraspp_mobilenet_v3_large_kelp.py",
          "train",
          "/data",
          "/checkpoints",
          "--name=lr_aspp_mussels",
          "--num_classes=2",
          "--lr=0.0003",
          "--weight_decay=0.001",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--gpus=-1",
          "--benchmark",
          "--max_epochs=10",
          "--batch_size=2",
      ]

  mussels-train-deeplabv3-resnet101:
    command:
      [
          "python",
          "lit_deeplabv3_resnet101_kelp.py",
          "train",
          "/data",
          "/checkpoints",
          "--name=deeplab_mussels",
          "--num_classes=2",
          "--lr=0.001",
          "--backbone_lr=0.0001",
          "--weight_decay=0.001",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--gpus=-1",
          "--benchmark",
          "--max_epochs=10",
          "--batch_size=2",
          "--unfreeze_backbone_epoch=1000"
      ]

  kelp-pa-train-lraspp-mobilenetv3:
    command:
      [
          "python",
          "lit_lraspp_mobilenet_v3_large_kelp.py",
          "train",
          "/data",
          "/checkpoints",
          "--name=lr_aspp_kelp_pa",
          "--num_classes=2",
          "--lr=0.001",
          "--weight_decay=0.001",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--gpus=-1",
          "--benchmark",
          "--max_epochs=10",
          "--batch_size=2",
      ]

  kelp-pa-train-deeplabv3-resnet101:
    command:
      [
          "python",
          "lit_deeplabv3_resnet101_kelp.py",
          "train",
          "/data",
          "/checkpoints",
          "--name=deeplab_kelp_pa",
          "--num_classes=2",
          "--lr=0.001",
          "--backbone_lr=0.0001",
          "--weight_decay=0.001",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--gpus=-1",
          "--benchmark",
          "--max_epochs=10",
          "--batch_size=2",
          "--unfreeze_backbone_epoch=1000"
      ]

  kelp-species-train-lraspp-mobilenetv3:
    command:
      [
          "python",
          "lit_lraspp_mobilenet_v3_large_kelp.py",
          "train",
          "/data",
          "/checkpoints",
          "--name=lr_aspp_kelp_species",
          "--num_classes=3",
          "--ignore_index=1",
          "--lr=0.0005",
          "--weight_decay=0.001",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--gpus=-1",
          "--benchmark",
          "--max_epochs=10",
          "--batch_size=2",
      ]

  kelp-species-train-deeplabv3-resnet101:
    command:
      [
          "python",
          "lit_deeplabv3_resnet101_kelp.py",
          "train",
          "/data",
          "/checkpoints",
          "--name=deeplab_kelp_species",
          "--num_classes=3",
          "--ignore_index=1",
          "--lr=0.001",
          "--backbone_lr=0.0001",
          "--weight_decay=0.001",
          "--gradient_clip_val=0.5",
          "--pa_weights=/data/best-val_miou=0.9393-epoch=97-step=34789.pt",
          "--accelerator=gpu",
          "--gpus=-1",
          "--benchmark",
          "--max_epochs=10",
          "--batch_size=2",
          "--unfreeze_backbone_epoch=1000"
      ]

volumes:
  checkpoints:
  torch_cache:
