version: "3.9"

# Default config to use all GPUs
x-deploy: &default-deploy
  replicas: 1
  resources:
#    limits:
#      memory: 8G
    reservations:
      memory: 2G
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  tensorboard:
    image: tensorflow/tensorflow:2.5.1
    env_file: ".env"
    tty: true
    stdin_open: true
    volumes:
      - "/mnt/data/presence/checkpoints:/checkpoints"
    ports:
      - "0.0.0.0:80:6006"
    command: [
        "tensorboard",
        "--logdir=/checkpoints/",
        "--host=0.0.0.0",
        "--port=6006"
    ]

  nvitop:
    image: hakaiinstitute/nvitop
    build:
      context: "https://github.com/Syllo/nvtop.git"
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    deploy: *default-deploy
    pid: "host"

  mussels-train-lraspp-mobilenetv3:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/mussels/Feb2022/data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
          "python",
          "lit_lraspp_mobilenet_v3_large.py",
          "/data",
          "s3a://hakai-deep-learning-datasets/checkpoints",
          "--name=lr_aspp_mussels",
          "--num_classes=2",
          "--lr=0.35",
          "--weight_decay=3e-6",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--strategy=ddp",
          "--gpus=-1",
          "--benchmark",
          "--sync_batchnorm",
          "--max_epochs=100",
#          "--swa_epoch_start=75",
          "--batch_size=16",
          "--precision=16",
      ]

  mussels-train-deeplabv3-resnet101:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/mussels/Feb2022/data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
          "python",
          "lit_deeplabv3_resnet101.py",
          "/data",
          "s3a://hakai-deep-learning-datasets/checkpoints",
          "--name=deeplab_mussels",
          "--num_classes=2",
          "--lr=0.35",
          "--weight_decay=3e-6",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--strategy=ddp",
          "--gpus=-1",
          "--benchmark",
          "--sync_batchnorm",
          "--unfreeze_backbone_epoch=0",
          "--train_backbone_bn",
          "--max_epochs=100",
          "--batch_size=8",
          "--precision=16",
      ]

  mussels-train-unet:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/mussels/Feb2022/data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
        "python",
        "lit_unet.py",
        "train",
        "/data",
        "s3a://hakai-deep-learning-datasets/checkpoints",
        "--name=unet_mussels",
        "--num_classes=2",
        "--lr=0.35",
        "--weight_decay=3e-6",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--strategy=ddp",
        "--gpus=-1",
        "--benchmark",
        "--sync_batchnorm",
        "--max_epochs=100",
        "--batch_size=8",
        "--precision=16",
      ]

  kelp-pa-train-lraspp-mobilenetv3:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/presence/data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
          "python",
          "lit_lraspp_mobilenet_v3_large.py",
          "/data",
          "s3a://hakai-deep-learning-datasets/checkpoints",
          "--name=lr_aspp_kelp_pa",
          "--num_classes=2",
          "--lr=0.35",
          "--weight_decay=3e-6",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--strategy=ddp",
          "--gpus=-1",
          "--benchmark",
          "--sync_batchnorm",
          "--max_epochs=100",
          "--batch_size=16",
          "--precision=16",
      ]

  kelp-pa-aco-train-lraspp-mobilenetv3:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/presence/data/Apr2022ACO:/data:ro"
      - "/mnt/data/presence/weights:/weights:ro"
      - "/mnt/data/presence/checkpoints:/checkpoints"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
        "python",
        "lit_lraspp_mobilenet_v3_large.py",
        "/data",
        "/checkpoints",
        "--name=lr_aspp_kelp_pa_aco",
        "--num_classes=2",
        "--weights=/weights/best-val_miou=0.8023-epoch=18-step=17593.pt",
        "--batch_size=16",
        "--keep_pretrained_output_layers",
        "--weight_decay=3e-5",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--devices=auto",
        #"--strategy=ddp_find_unused_parameters_false",
        "--benchmark",
        "--sync_batchnorm",
        "--max_epochs=30",
        "--batch_size=16",
        "--precision=16",
      ]

  kelp-pa-train-deeplabv3-resnet101:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/presence/data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
          "python",
          "lit_deeplabv3_resnet101.py",
          "/data",
          "s3a://hakai-deep-learning-datasets/checkpoints",
          "--name=deeplab_kelp_pa",
          "--num_classes=2",
          "--lr=0.001",
          "--weight_decay=0.001",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--strategy=ddp",
          "--gpus=-1",
          "--benchmark",
          "--sync_batchnorm",
          "--max_epochs=100",
          "--batch_size=8",
          "--precision=16",
      ]

  kelp-pa-train-unet:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/presence/data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
          "python",
          "lit_unet.py",
          "train",
          "/data",
          "s3a://hakai-deep-learning-datasets/checkpoints",
          "--name=unet_kelp_pa",
          "--num_classes=2",
          "--lr=0.35",
          "--weight_decay=3e-6",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--strategy=ddp",
          "--gpus=-1",
          "--benchmark",
          "--sync_batchnorm",
          "--max_epochs=100",
          "--batch_size=8",
          "--precision=16",
      ]

  kelp-species-train-lraspp-mobilenetv3:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/species/data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
          "python",
          "lit_lraspp_mobilenet_v3_large.py",
          "/data",
          "s3a://hakai-deep-learning-datasets/checkpoints",
          "--name=lr_aspp_kelp_species",
          "--num_classes=3",
          "--ignore_index=1",
          "--lr=0.0005",
          "--weight_decay=3e-6",
          "--gradient_clip_val=0.5",
          "--accelerator=gpu",
          "--strategy=ddp",
          "--gpus=-1",
          "--benchmark",
          "--sync_batchnorm",
          "--max_epochs=100",
          "--swa_epoch_start=75",
          "--batch_size=16",
          "--precision=16",
      ]

  kelp-species-train-deeplabv3-resnet101:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/species/data:/data:ro"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    deploy: *default-deploy
    command:
      [
          "python",
          "lit_deeplabv3_resnet101.py",
          "/data",
          "s3a://hakai-deep-learning-datasets/checkpoints",
          "--name=deeplab_kelp_species",
          "--num_classes=3",
          "--ignore_index=1",
          "--lr=0.35",
          "--weight_decay=3e-6",
          "--gradient_clip_val=0.5",
          "--pa_weights=/data/best-val_miou=0.9393-epoch=97-step=34789.pt",
          "--accelerator=gpu",
          "--strategy=ddp",
          "--gpus=-1",
          "--benchmark",
          "--sync_batchnorm",
          "--max_epochs=100",
          "--batch_size=8",
          "--precision=16",
      ]

volumes:
  torch_cache:
