version: "3.9"

services:
  tensorboard:
    volumes:
      - "checkpoints:/checkpoints:ro"
      - "./data:/data:ro"
    command: [
      "tensorboard",
      "--logdir=/checkpoints",
      "--host=0.0.0.0",
      "--port=6006",
      "--load_fast=false",
    ]

  mussels-train-lraspp-mobilenetv3:
    volumes:
      - "checkpoints:/checkpoints"
      - "./data:/data:ro"
    command:
      [
        "python",
        "lit_lraspp_mobilenet_v3_large.py",
        "train",
        "/data",
        "/checkpoints",
        "--name=lr_aspp_mussels",
        "--num_classes=2",
        "--lr=0.35",
        "--weight_decay=3e-6",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--gpus=-1",
        "--max_epochs=2",
        "--swa_epoch_start=7",
        "--batch_size=2",
        "--overfit_batches=2",
      ]

  mussels-train-deeplabv3-resnet101:
    volumes:
      - "checkpoints:/checkpoints"
      - "./data:/data:ro"
    command:
      [
        "python",
        "lit_deeplabv3_resnet101.py",
        "train",
        "/data/mussels",
        "/checkpoints",
        "--name=deeplab_mussels",
        "--num_classes=2",
        "--lr=0.35",
        "--weight_decay=3e-6",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--gpus=-1",
        "--benchmark",
        "--max_epochs=10",
        "--batch_size=2",
        "--num_workers=2",
        "--unfreeze_backbone_epoch=1000",
        "--no_train_backbone_bn",
        "--overfit_batches=2",
        "--log_every_n_steps=2",
      ]

  kelp-pa-train-lraspp-mobilenetv3:
    volumes:
      - "checkpoints:/checkpoints"
      - "/mnt/Scratch/Taylor/ml/kelp_presence_data/Jan2022:/data:ro"
    tty: true
    stdin_open: true
    command:
      [
        "python",
        "lit_lraspp_mobilenet_v3_large.py",
        "train",
        "/data",
        "/checkpoints",
        "--name=lr_aspp_kelp_pa",
        "--num_classes=2",
        "--lr=0.35",
        "--weight_decay=3e-6",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--gpus=-1",
        "--max_epochs=2",
        "--swa_epoch_start=75",
        "--batch_size=4",
        "--overfit_batches=100",
      ]

  kelp-pa-train-deeplabv3-resnet101:
    volumes:
      - "/home/taylor/PycharmProjects/hakai-ml-train/data/kelp_pa_aco:/data:ro"
      - "/home/taylor/PycharmProjects/hakai-ml-train/checkpoints/kelp_pa:/checkpoints"
    command:
      [
        "python",
        "lit_deeplabv3_resnet101.py",
        "/data",
        "/checkpoints",
        "--name=deeplab_resnet101_kelp_pa",
        "--num_classes=2",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--devices=auto",
        "--sync_batchnorm",
        "--max_epochs=3",
        "--batch_size=2",
        "--backbone_finetuning_epoch=100",
        '--limit_train_batches=10',
        "--limit_val_batches=10",
        "--limit_test_batches=10",
        "--log_every_n_steps=5"
      ]

  kelp-species-train-lraspp-mobilenetv3:
    volumes:
      - "checkpoints:/checkpoints"
      - "./data:/data:ro"
    command:
      [
        "python",
        "lit_lraspp_mobilenet_v3_large.py",
        "train",
        "/data/kelp_species",
        "/checkpoints",
        "--name=lr_aspp_kelp_species",
        "--num_classes=3",
        "--ignore_index=1",
        "--lr=0.35",
        "--weight_decay=3e-6",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--gpus=-1",
        #          "--benchmark",
        "--max_epochs=10",
        "--swa_epoch_start=75",
        "--batch_size=4",
        #          "--overfit_batches=10",
      ]

  kelp-species-train-deeplabv3-resnet101:
    volumes:
      - "./checkpoints:/checkpoints"
      - "./data:/data:ro"
    command:
      [
        "python",
        "lit_deeplabv3_resnet101.py",
        "train",
        "/data/kelp_species",
        "/checkpoints",
        "--name=deeplab_kelp_species",
        "--num_classes=3",
        "--ignore_index=1",
        "--lr=0.35",
        "--weight_decay=3e-6",
        "--gradient_clip_val=0.5",
        "--pa_weights=/data/best-val_miou=0.9393-epoch=97-step=34789.pt",
        "--accelerator=gpu",
        "--gpus=-1",
        "--benchmark",
        "--max_epochs=10",
        "--batch_size=2",
        "--unfreeze_backbone_epoch=1000",
        "--no_train_backbone_bn",
        "--overfit_batches=2",
        "--log_every_n_steps=2",
      ]

volumes:
  checkpoints:
