version: "3.9"

# Default config to use all GPUs
x-deploy: &default-deploy
  replicas: 1
  resources:
    #    limits:
    #      memory: 8G
    reservations:
      memory: 2G
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  tensorboard:
    image: tensorflow/tensorflow:2.5.1
    env_file: ".env"
    tty: true
    stdin_open: true
    volumes:
      - "/mnt/data/presence/checkpoints:/checkpoints"
    ports:
      - "0.0.0.0:80:6006"
    command: [
      "tensorboard",
      "--logdir=/checkpoints/",
      "--host=0.0.0.0",
      "--port=6006"
    ]

  nvitop:
    image: hakaiinstitute/nvitop
    build:
      context: "https://github.com/Syllo/nvtop.git"
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    deploy: *default-deploy
    pid: "host"

  mussels-train-unet:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/mussels/data/Aug2022:/data:ro"
      - "/mnt/data/mussels/checkpoints:/checkpoints"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    shm_size: '2gb'
    deploy: *default-deploy
    command:
      [
        "python",
        "train.py",
        "unet",
        "/data",
        "/checkpoints",
        "--name=mussels_pa_unet",
        "--num_classes=2",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--devices=auto",
        "--sync_batchnorm",
        "--max_epochs=100",
        "--precision=16",
        "--batch_size=32",
        "--init_lr=0.01",
        "--init_alpha=0.7",
        "--init_weight_decay=0.0003",
        "--benchmark",
      ]

  mussels-train-lraspp:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/mussels/data/Aug2022:/data:ro"
      - "/mnt/data/mussels/checkpoints:/checkpoints"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    shm_size: '2gb'
    deploy: *default-deploy
    command:
      [
        "python",
        "train.py",
        "lraspp",
        "/data",
        "/checkpoints",
        "--name=mussels_pa_lraspp",
        "--num_classes=2",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--devices=auto",
        "--sync_batchnorm",
        "--max_epochs=100",
        "--precision=16",
        "--batch_size=32",
        "--init_lr=0.003",
        "--init_alpha=0.7",
        "--init_weight_decay=0.001",
        "--benchmark",
      ]

  mussels-train-deeplab:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/mussels/data/Aug2022:/data:ro"
      - "/mnt/data/mussels/checkpoints:/checkpoints"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    shm_size: '2gb'
    deploy: *default-deploy
    command:
      [
        "python",
        "train.py",
        "deeplab",
        "/data",
        "/checkpoints",
        "--name=mussels_pa_deeplab",
        "--num_classes=2",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--devices=auto",
        "--sync_batchnorm",
        "--max_epochs=20",
        "--precision=16",
        "--batch_size=8",
        "--init_lr=0.01",
        "--init_alpha=0.7",
        "--init_weight_decay=0",
        "--benchmark",
        "--backbone_finetuning_epoch=16",
      ]

  kelp-pa-train-unet:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/presence/data/July2022:/data:ro"
      - "/mnt/data/presence/checkpoints:/checkpoints"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    shm_size: '2gb'
    deploy: *default-deploy
    command:
      [
        "python",
        "train.py",
        "unet",
        "/data",
        "/checkpoints",
        "--name=kelp_pa_unet",
        "--num_classes=2",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--devices=auto",
        "--sync_batchnorm",
        "--max_epochs=100",
        "--precision=16",
        "--batch_size=64",
        "--strategy=ddp_find_unused_parameters_false",
        "--benchmark",
      ]

  kelp-pa-train-lraspp:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/presence/data/July2022:/data:ro"
      - "/mnt/data/presence/checkpoints:/checkpoints"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    shm_size: '2gb'
    deploy: *default-deploy
    command:
      [
        "python",
        "train.py",
        "lraspp",
        "/data",
        "/checkpoints",
        "--name=kelp_pa_lraspp",
        "--num_classes=2",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--devices=auto",
        "--sync_batchnorm",
        "--max_epochs=100",
        "--precision=16",
        "--batch_size=32",
        "--init_lr=0.003",
        "--init_alpha=0.7",
        "--init_weight_decay=0.001",
        "--benchmark",
      ]

  kelp-pa-train-deeplab:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/presence/data/July2022:/data:ro"
      - "/mnt/data/presence/checkpoints:/checkpoints"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    shm_size: '2gb'
    deploy: *default-deploy
    command:
      [
        "python",
        "train.py",
        "deeplab",
        "/data",
        "/checkpoints",
        "--name=kelp_pa_deeplab",
        "--num_classes=2",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--devices=auto",
        "--sync_batchnorm",
        "--max_epochs=100",
        "--precision=16",
        "--batch_size=8",
        "--init_lr=0.001",
        "--init_alpha=0.7",
        "--init_weight_decay=0.001",
        "--strategy=ddp_find_unused_parameters_false",
        "--benchmark",
      ]

  kelp-species-train-lraspp:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/species/data/Apr2022:/data:ro"
      - "/mnt/data/presence/weights:/weights:ro"
      - "/mnt/data/species/checkpoints:/checkpoints"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    shm_size: '2gb'
    deploy: *default-deploy
    command:
      [
        "python",
        "train.py",
        "lraspp",
        "/data",
        "/checkpoints",
        "--name=kelp_species_lraspp",
        "--num_classes=4",
        "--ignore_index=1",
        "--weights=/weights/best-val_miou=0.8023-epoch=18-step=17593.pt",
        "--drop_output_layer_weights",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--devices=auto",
        "--sync_batchnorm",
        "--max_epochs=30",
        "--precision=16",
        "--batch_size=16",
      ]

  kelp-species-train-deeplab:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/species/data/Apr2022:/data:ro"
      - "/mnt/data/species/weights:/weights:ro"
      - "/mnt/data/species/checkpoints:/checkpoints"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    shm_size: '2gb'
    deploy: *default-deploy
    command:
      [
        "python",
        "train.py",
        "deeplab",
        "/data",
        "/checkpoints",
        "--name=kelp_species_species",
        "--num_classes=4",
        "--ignore_index=1",
        "--weights=/data/best-val_miou=0.9393-epoch=97-step=34789.pt",
        "--drop_output_layer_weights",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--devices=auto",
        "--sync_batchnorm",
        "--max_epochs=30",
        "--precision=16",
        "--batch_size=8",
      ]

  kelp-pa-aco-train-lraspp:
    image: hakaiinstitute/pytorch-lightning
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    env_file: ".env"
    volumes:
      - "/mnt/data/presence/data/Apr2022ACO:/data:ro"
      - "/mnt/data/presence/weights:/weights:ro"
      - "/mnt/data/presence/checkpoints:/checkpoints"
      - "torch_cache:/root/.cache/torch"
    ipc: host
    shm_size: '2gb'
    deploy: *default-deploy
    command:
      [
        "python",
        "train.py",
        "",
        "/data",
        "/checkpoints",
        "--name=lr_aspp_kelp_pa_aco",
        "--num_classes=2",
        "--weights=/weights/best-val_miou=0.8023-epoch=18-step=17593.pt",
        "--batch_size=16",
        "--gradient_clip_val=0.5",
        "--accelerator=gpu",
        "--devices=auto",
        #"--strategy=ddp_find_unused_parameters_false",
        "--sync_batchnorm",
        "--max_epochs=20",
        "--precision=16",
      ]

volumes:
  torch_cache:
