name: uav-classif
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - fire
  - loguru
  - pip
  - python=3.8
  - rasterio
  - scikit-learn
  - tensorboard
  - torchaudio
  - torchvision
  - tqdm>=4.46
  - pip:
    - geotiff_crop_dataset
    - git+https://github.com/PyTorchLightning/pytorch-lightning
    - lightning-bolts
    - test_tube
    - torchmetrics