name: uav-classif
channels:
  - conda-forge
  - defaults
dependencies:
#  - nvidia::cudatoolkit=11.1
  - fire
  - gdal>=3.2
  - loguru
  - pip
  - pyinstaller>=4.3
  - python=3.8
#  - pytorch-lightning
#  - pytorch::pytorch>=1.8
  - scikit-image
  - scikit-learn
  - tensorboard
#  - pytorch::torchaudio
#  - pytorch::torchvision>=0.9
  - tqdm
  - rasterio>=1.2
  - pip:
    - geotiff_crop_dataset
#    - lightning-bolts
    - PySide2
    - test_tube
#    - torchmetrics
