name: hakai-ml-train
channels:
  - pytorch
  - conda-forge
dependencies:
  - conda-forge::loguru
  - conda-forge::pytorch-lightning>=1.6
  - conda-forge::tensorboard
  - conda-forge::torchmetrics
  - conda-forge::tqdm
  - nvidia::cudatoolkit=10.2
  - python=3.9
  - pytorch::pytorch>=1.11
  - pytorch::torchaudio
  - pytorch::torchvision
  - huggingface::transformers
  - pip
  - pip:
    - lightning-bolts
    - segmentation-models-pytorch
