name: ml-train
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - conda-forge::cudatoolkit=11.6
  - conda-forge::jupyter
  - conda-forge::loguru
  - conda-forge::optuna
  - conda-forge::pytorch-lightning>=1.5.0,<1.6.0
  - conda-forge::s3fs
  - conda-forge::tensorboard
  - conda-forge::torchmetrics
  - conda-forge::tqdm
  - pytorch::pytorch>=1.11.0
  - pytorch::torchaudio
  - pytorch::torchvision
  - pip
  - pip:
    - lightning-bolts
    - segmentation-models-pytorch