name: uav
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=10.2
  - torchvision
  - pytorch>=1.6
  - pytorch-lightning
  - tensorboard
  - rasterio
  - tqdm>=4.46
  - fire
  - scikit-learn