name: ml-train
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - nvidia::pytorch-cuda=12.1
  - conda-forge::jupyter
  - conda-forge::lightning
  - conda-forge::torchmetrics>=0.11.0
  - conda-forge::tqdm
  - conda-forge::onnx
  - conda-forge::pydantic
  - conda-forge::pyyaml
  - conda-forge::monai
  - pip
  - pip:
    - torchseg
    - einops
    - finetuning_scheduler
#    - unified-focal-loss-pytorch
    - albumentations
    - wandb
