name: hakai-ml-train
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - conda-forge::loguru
  - conda-forge::jupyter
  - conda-forge::pytorch-lightning>=1.6
  - conda-forge::s3fs
  - conda-forge::tensorboard
  - conda-forge::torchmetrics
  - conda-forge::tqdm
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch>=1.11
  - pytorch::torchaudio
  - pytorch::torchvision
  - pip
  - pip:
    - "ray[tune]"
    - scikit-optimize
    - lightning-bolts
    - segmentation-models-pytorch