name: hakai-ml-train
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - nvidia::cudatoolkit=10.2
  - loguru
  - python=3.9
  - pytorch-lightning
  - pytorch::pytorch>=1.10
  - tensorboard
  - pytorch::torchaudio
  - pytorch::torchvision
  - tqdm
  - pip
  - pip:
    - geotiff_crop_dataset
    - lightning-bolts
    - test_tube
    - torchmetrics
