name: uav-classif
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.1
  - loguru
  - pip
  - pyinstaller>=4.3
  - python=3.8
  - pytorch-lightning
  - pytorch>=1.8.1
  - tensorboard
  - torchaudio
  - torchvision>=0.9.0
  - tqdm
  - pip:
    - geotiff_crop_dataset
    - lightning-bolts
    - PySide2
    - rasterio
    - test_tube
    - torchmetrics
