name: test
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit=10.1
  - torchvision
  - pytorch=1.5.0
  - rasterio
  - tensorboard
  - tqdm
  - fire
  - geopandas
  - numpy
