name: ml-train
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - conda-forge::cudatoolkit=11.3
  - conda-forge::jupyter
  - conda-forge::loguru
  - conda-forge::pytorch-lightning
  - conda-forge::s3fs
  - conda-forge::tensorboard
  - conda-forge::torchmetrics<=0.9.3
  - conda-forge::tqdm
  - pytorch::pytorch>=1.12.1
  - pytorch::torchaudio
  - pytorch::torchvision
  - pip
  - pip:
    - lightning-bolts
    - segmentation-models-pytorch
    - einops