segmentation_model_cls: SMPSegmentationModel
enable_logging: true
tags:
  - mussels
  - May2024

num_bands: &num_bands 3
num_classes: &num_classes 1
tile_size: &tile_size 1024
batch_size: &batch_size 3
max_epoch: &max_epoch 20

segmentation_config:
  architecture: "DPT"
  backbone: "tu-mobilevitv2_175.cvnets_in22k_ft_in1k"
  freeze_encoder: false
  opts:
    encoder_weights: cvnets_in22k_ft_in1k
  num_classes: *num_classes
  ignore_index: 2
  lr: 0.0003
  weight_decay: 0.01
  num_bands: *num_bands
  tile_size: *tile_size
  batch_size: *batch_size
  max_epochs: *max_epoch
  warmup_period: 0.1
  loss:
    name: "LovaszLoss"
    opts:
      mode: "binary"
      from_logits: true

data_module:
  data_dir: "/home/taylor/data/MP-RGB-May2024-1024-1024"
  tile_size: *tile_size
  num_classes: *num_classes
  batch_size: *batch_size
  fill_value: 0
  fill_mask: 0
  num_workers: 8
  pin_memory: true
  persistent_workers: true

trainer:
  accumulate_grad_batches: 8
  gradient_clip_val: 0.5
  max_epochs: *max_epoch
  precision: "bf16-mixed"
  deterministic: false

logging:
  project: "kom-mussels-rgb"
  name: "DPT-mobilevitv2_175"
  save_dir: "./checkpoints"
  log_model: true
