seed_everything: 42

model:
  class_path: "src.models.smp.KelpSpeciesModel"
  init_args:
    architecture: "Segformer"
    backbone: "mit_b3"
    model_opts:
      encoder_weights: imagenet
      in_channels: 4
    num_classes: 3
    ignore_index: &ignore_index -100
    lr: 3e-4
    wd: 0.0001
    b1: 0.9
    b2: 0.999
    loss: "LovaszLoss"
    loss_opts:
      mode: "multiclass"
      ignore_index: *ignore_index
      from_logits: true

data:
  class_path: "src.data.DataModule"
  init_args:
    train_chip_dir: "/home/taylor/data/KS-RGBI-Jul2025-1024-1024/train"
    val_chip_dir: "/home/taylor/data/KS-RGBI-Jul2025-1024-1024-full/val"
    test_chip_dir: "/home/taylor/data/KS-RGBI-Jul2025-1024-1024-full/test"
    batch_size: 3
    num_workers: 8
    pin_memory: true
    persistent_workers: true
    train_transforms:
      __version__: 2.0.9
      transform:
        __class_fullname__: Compose
        additional_targets: { }
        bbox_params: null
        is_check_shapes: true
        keypoint_params: null
        p: 1
        seed: null
        transforms:
          - __class_fullname__: D4
            p: 1.0
          - __class_fullname__: Normalize
            max_pixel_value: 255.0
            mean:
              - 0.4
              - 0.45
              - 0.474
              - 0.448
            normalization: standard
            p: 1.0
            std:
              - 0.328
              - 0.303
              - 0.284
              - 0.349
          - __class_fullname__: ToTensorV2
            p: 1.0
            transpose_mask: false
    test_transforms:
      __version__: 2.0.9
      transform:
        __class_fullname__: Compose
        additional_targets: { }
        bbox_params: null
        is_check_shapes: true
        keypoint_params: null
        p: 1
        seed: null
        transforms:
          - __class_fullname__: Normalize
            max_pixel_value: 255.0
            mean:
              - 0.4
              - 0.45
              - 0.474
              - 0.448
            normalization: standard
            p: 1.0
            std:
              - 0.328
              - 0.303
              - 0.284
              - 0.349
          - __class_fullname__: ToTensorV2
            p: 1.0
            transpose_mask: false

trainer:
  accelerator: auto
  devices: auto
  precision: bf16-mixed
  log_every_n_steps: 50
  max_epochs: 20
  accumulate_grad_batches: 8
  gradient_clip_val: 0.5
  detect_anomaly: false
  default_root_dir: checkpoints
  fast_dev_run: False
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: hakai
        project: kom-kelp-rgbi
        name: segformer_b3
        group: Jul2025
        log_model: true
        tags:
          - kelp
          - Jul2025
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        auto_insert_metric_name: False
        filename: kelp_rgbi_segformer_b3_epoch-{epoch:02d}_val-iou-{val/iou_epoch:.4f}
        monitor: val/iou_epoch
        mode: max
        save_last: True
        save_top_k: 2
        save_weights_only: True
        verbose: True
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
