segmentation_model_cls: UnetPlusPlus
enable_logging: true
tags:
  - kp-rgb
  - Jan2024

num_bands: &num_bands 3
num_classes: &num_classes 1
tile_size: &tile_size 1024
batch_size: &batch_size 6
max_epoch: &max_epoch 100

segmentation_config:
  backbone: "efficientnet-b4"
  num_classes: *num_classes
  ignore_index: 2
  lr: 0.003
  weight_decay: 0.0001
  num_bands: *num_bands
  tile_size: *tile_size
  batch_size: *batch_size
  max_epochs: *max_epoch
  warmup_period: 0.02
  opts:
    decoder_attention_type: "scse"
  loss:
    name: "FocalTverskyLoss"
    opts:
      delta: 0.5
      gamma: 2.0

data_module:
  data_dir: "/home/taylor/data/KP-RGB-Jan2024/"
  tile_size: *tile_size
  num_classes: *num_classes
  batch_size: *batch_size
  fill_value: 0
  num_workers: 4
  pin_memory: true
  persistent_workers: true

trainer:
  accumulate_grad_batches: 32
  gradient_clip_val: 0.5
  max_epochs: *max_epoch
  precision: "16-mixed"

logging:
  project: "kom-kelp-pa-rgb"
  name: "UNetPlusPlus-effb4"
  save_dir: "./checkpoints"
  log_model: true

