segmentation_model_cls: SMPSegmentationModel
enable_logging: true
tags:
  - ks-rgb
  - Jan2024

num_bands: &num_bands 3
num_classes: &num_classes 2
tile_size: &tile_size 1024
batch_size: &batch_size 2
max_epoch: &max_epoch 20

segmentation_config:
  architecture: "Segformer"
  backbone: "mit_b3"
  freeze_encoder: false
  opts:
    encoder_weights: imagenet
  num_classes: *num_classes
  ignore_index: 2
  lr: 0.0003
  weight_decay: 0.01
  num_bands: *num_bands
  tile_size: *tile_size
  batch_size: *batch_size
  max_epochs: *max_epoch
  task: "multiclass"
  warmup_period: 0.1
  loss:
    name: "FocalDiceComboLoss"
    opts:
      dice_kwargs:
        mode: "multiclass"
        from_logits: true
      focal_kwargs:
        mode: "multiclass"
        alpha: null
        gamma: 2.0
        reduction: "mean"

data_module:
  data_dir: "/home/taylor/data/KS-RGB-Jan2024/"
  tile_size: *tile_size
  num_classes: *num_classes
  batch_size: *batch_size
  fill_value: 0
  fill_mask: 2
  num_workers: 8
  pin_memory: true
  persistent_workers: false

trainer:
  accumulate_grad_batches: 8
  gradient_clip_val: 0.5
  max_epochs: *max_epoch
  precision: "bf16-mixed"
  deterministic: false

logging:
  project: "kom-kelp-sp-rgb"
  name: "Segformer-mit-b3"
  save_dir: "./checkpoints"
  log_model: true
