seed_everything: 42

model:
  class_path: "src.models.smp.SMPMulticlassSegmentationModel"
  init_args:
    architecture: "EoMT"
    encoder_name: "tu-vit_large_patch16_dinov3.sat493m"
    model_opts:
      encoder_weights: true
      in_channels: 3
      decoder_readout: "cat"
      dynamic_img_size: true
      img_size: 1024
    num_classes: 3
    ignore_index: &ignore_index -100
    optimizer_class: torch.optim.AdamW
    optimizer_opts:
      lr: 3e-4
      weight_decay: 0.03
      betas:
        - 0.9
        - 0.95
    lr_scheduler_class: src.schedulers.LinearWarmupCosineDecayLR
    lr_scheduler_opts:
      warmup_steps: 7
      min_lr: 1e-6
    lr_scheduler_interval: epoch
    loss: "LabelSmoothingLovasz"
    loss_opts:
      mode: "multiclass"
      smoothing: 0.1
      lovasz_weight: 0.5
      ignore_index: *ignore_index
    class_names:
      - bg
      - mussels
      - goosenecks

data:
  class_path: "src.data.WebDataModule"
  init_args:
    train_chip_dir: "/home/taylor/data/MGP-RGB-Feb2026-1024-512-full-webds"
    val_chip_dir: "/home/taylor/data/MGP-RGB-Feb2026-1024-1024-full-webds"
    test_chip_dir: "/home/taylor/data/MGP-RGB-Feb2026-1024-1024-full-webds"
    batch_size: 6
    num_workers: 8
    pin_memory: true
    persistent_workers: true
    train_transforms:
      __version__: 2.0.8
      transform:
        __class_fullname__: Compose
        additional_targets: { }
        bbox_params: null
        is_check_shapes: true
        keypoint_params: null
        seed: 42
        p: 1
        transforms:
          - __class_fullname__: D4
            p: 1.0
          - __class_fullname__: Affine
            balanced_scale: false
            border_mode: 0
            fill: 0.0
            fill_mask: 0.0
            fit_output: false
            interpolation: 1
            keep_ratio: false
            mask_interpolation: 0
            p: 0.5
            rotate:
              - -15.0
              - 15.0
            rotate_method: largest_box
            scale:
              x:
                - 0.9
                - 1.1
              y:
                - 0.9
                - 1.1
            shear:
              x:
                - 0.0
                - 0.0
              y:
                - 0.0
                - 0.0
            translate_percent: null
            translate_px:
              x:
                - 0
                - 0
              y:
                - 0
                - 0
          - __class_fullname__: OneOf
            p: 0.5
            transforms:
              - __class_fullname__: RandomBrightnessContrast
                brightness_by_max: true
                brightness_limit:
                  - -0.2
                  - 0.2
                contrast_limit:
                  - -0.2
                  - 0.2
                ensure_safe_range: false
                p: 1.0
              - __class_fullname__: HueSaturationValue
                hue_shift_limit:
                  - -10.0
                  - 10.0
                p: 1.0
                sat_shift_limit:
                  - -20.0
                  - 20.0
                val_shift_limit:
                  - -15.0
                  - 15.0
              - __class_fullname__: ColorJitter
                brightness:
                  - 0.85
                  - 1.15
                contrast:
                  - 0.85
                  - 1.15
                hue:
                  - -0.05
                  - 0.05
                p: 1.0
                saturation:
                  - 0.8
                  - 1.2
          - __class_fullname__: RandomToneCurve
            p: 0.2
            per_channel: false
            scale: 0.15
          - __class_fullname__: CLAHE
            clip_limit:
              - 1.0
              - 2.0
            p: 0.15
            tile_grid_size:
              - 8
              - 8
          - __class_fullname__: OneOf
            p: 0.15
            transforms:
              - __class_fullname__: Sharpen
                alpha:
                  - 0.2
                  - 0.5
                kernel_size: 5
                lightness:
                  - 0.5
                  - 1.0
                method: kernel
                p: 1.0
                sigma: 1.0
              - __class_fullname__: UnsharpMask
                alpha:
                  - 0.2
                  - 0.5
                blur_limit:
                  - 3
                  - 7
                p: 1.0
                sigma_limit:
                  - 0.0
                  - 0.0
                threshold: 10
          - __class_fullname__: OneOf
            p: 0.25
            transforms:
              - __class_fullname__: GaussNoise
                mean_range:
                  - 0.0
                  - 0.0
                noise_scale_factor: 1.0
                p: 1.0
                per_channel: true
                std_range:
                  - 0.02
                  - 0.05
              - __class_fullname__: ISONoise
                color_shift:
                  - 0.01
                  - 0.05
                intensity:
                  - 0.1
                  - 0.3
                p: 1.0
          - __class_fullname__: OneOf
            p: 0.15
            transforms:
              - __class_fullname__: GaussianBlur
                blur_limit:
                  - 3
                  - 5
                p: 1.0
                sigma_limit:
                  - 0.5
                  - 3.0
              - __class_fullname__: MedianBlur
                blur_limit:
                  - 3
                  - 5
                p: 1.0
          - __class_fullname__: OneOf
            p: 0.2
            transforms:
              - __class_fullname__: GridDropout
                fill: 0.0
                fill_mask: 0.0
                holes_number_xy: null
                p: 1.0
                random_offset: true
                ratio: 0.3
                shift_xy:
                  - 0
                  - 0
                unit_size_range: null
              - __class_fullname__: CoarseDropout
                fill: 0.0
                fill_mask: 0.0
                hole_height_range:
                  - 24
                  - 48
                hole_width_range:
                  - 24
                  - 48
                num_holes_range:
                  - 3
                  - 8
                p: 1.0
          - __class_fullname__: OneOf
            p: 0.15
            transforms:
              - __class_fullname__: ElasticTransform
                alpha: 1.0
                sigma: 50.0
                p: 1.0
              - __class_fullname__: GridDistortion
                num_steps: 5
                distort_limit: 0.3
                p: 1.0
          - __class_fullname__: Normalize
            max_pixel_value: 255.0
            mean:
              - 0.430
              - 0.411
              - 0.296
            normalization: standard
            p: 1.0
            std:
              - 0.213
              - 0.156
              - 0.143
          - __class_fullname__: ToTensorV2
            p: 1.0
            transpose_mask: false

    test_transforms:
      __version__: 2.0.8
      transform:
        __class_fullname__: Compose
        additional_targets: { }
        bbox_params: null
        is_check_shapes: true
        keypoint_params: null
        p: 1
        seed: 42
        transforms:
          - __class_fullname__: Normalize
            max_pixel_value: 255.0
            mean:
              - 0.430
              - 0.411
              - 0.296
            normalization: standard
            p: 1.0
            std:
              - 0.213
              - 0.156
              - 0.143
          - __class_fullname__: ToTensorV2
            p: 1.0
            transpose_mask: false

trainer:
  accelerator: auto
  devices: auto
  precision: bf16-mixed
  log_every_n_steps: 5
  max_epochs: 200
  accumulate_grad_batches: 8
  gradient_clip_val: 0.5
  detect_anomaly: false
  default_root_dir: checkpoints
  fast_dev_run: False
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: hakai
        project: kom-mussel-gooseneck-rgb
        name: dpt_dinov3_vitl16
        group: Mar2026
        log_model: true
        tags:
          - mussel_gooseneck
          - Mar2026
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        auto_insert_metric_name: False
        filename: mussel_gooseneck_rgb_dpt_dinov3_vitl16_epoch-{epoch:02d}_val-iou-{val/iou_epoch:.4f}
        monitor: val/iou_epoch
        mode: max
        save_last: True
        save_top_k: 2
        save_weights_only: False
        verbose: True
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/iou_epoch
        mode: max
        patience: 30
        verbose: true
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.BackboneFinetuning
      init_args:
        unfreeze_backbone_at_epoch: 100000
        backbone_initial_ratio_lr: 0.1
        should_align: true
        train_bn: true
        verbose: true
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
