wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705348644.424838
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 54
      - 55
      - 63
      - 74
      - 80
      - 103
      - 105
      2:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 54
      - 55
      - 63
      - 74
      - 80
      - 103
      - 105
      3:
      - 2
      - 23
      4: 3.11.6
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
