segmentation_model_cls: SMPSegmentationModel
enable_logging: true
tags:
  - kp-rgbi
  - Nov2023

num_bands: &num_bands 4
num_classes: &num_classes 1
tile_size: &tile_size 1024
batch_size: &batch_size 6
max_epoch: &max_epoch 20

segmentation_config:
  architecture: "UnetPlusPlus"
  backbone: "tf_efficientnetv2_s"
  freeze_encoder: false
  opts:
    encoder_weights: true
  num_classes: *num_classes
  ignore_index: 2
  lr: 0.0003
  weight_decay: 0.0001
  num_bands: *num_bands
  tile_size: *tile_size
  batch_size: *batch_size
  max_epochs: *max_epoch
  warmup_period: 0.1
  loss:
    name: "LovaszLoss"
    opts:
      mode: "binary"
      from_logits: true

data_module:
  data_dir: "/home/taylor/data/KP-ACO-RGBI-Nov2023/"
  tile_size: *tile_size
  num_classes: *num_classes
  batch_size: *batch_size
  fill_value: 0
  num_workers: 4
  pin_memory: true
  persistent_workers: true

trainer:
  accumulate_grad_batches: 32
  gradient_clip_val: 0.5
  max_epochs: *max_epoch
  precision: "16-mixed"
  deterministic: false

logging:
  project: "kom-kelp-pa-aco-rgbi"
  name: "UNetPP-efficientnetv2-s"
  save_dir: "./checkpoints"
  log_model: true

test_transforms:
  transform:
    __class_fullname__: Compose
    p: 1
    transforms:
      - __class_fullname__: PadIfNeeded
        border_mode: 4
        min_height: *tile_size
        min_width: *tile_size
        p: 1
      - __class_fullname__: RandomCrop
        height: *tile_size
        width: *tile_size
        p: 1
      - __class_fullname__: Normalize
        max_pixel_value: 255
        normalization: standard
        mean: [ 0.2716, 0.33, 0.3881, 0.2688 ]
        std: [ 0.1902, 0.1799, 0.1597, 0.2160 ]
        p: 1
      - __class_fullname__: ToTensorV2
        p: 1

train_transforms:
  transform:
    __class_fullname__: Compose
    p: 1
    transforms:
      - __class_fullname__: PadIfNeeded
        border_mode: 4
        min_height: *tile_size
        min_width: *tile_size
        p: 1
      - __class_fullname__: RandomCrop
        height: *tile_size
        width: *tile_size
        p: 1
      - __class_fullname__: D4
        p: 1
      - __class_fullname__: OneOf
        p: 0.5
        transforms:
          - __class_fullname__: RandomBrightnessContrast
            brightness_limit: 0.1
            contrast_limit: 0.1
            p: 1
      - __class_fullname__: OneOf
        p: 0.3
        transforms:
          - __class_fullname__: GaussNoise
            var_limit:
              - 5
              - 30
            p: 1
      - __class_fullname__: OneOf
        p: 0.3
        transforms:
          - __class_fullname__: MotionBlur
            p: 1
          - __class_fullname__: MedianBlur
            p: 1
          - __class_fullname__: GaussianBlur
            p: 1
      - __class_fullname__: OneOf
        p: 0.3
        transforms:
          - __class_fullname__: CoarseDropout
            max_holes: 4
            max_height: 16
            max_width: 16
            fill_value: 0
            p: 1
          - __class_fullname__: GridDistortion
            num_steps: 3
            distort_limit: 0.2
            p: 1
      - __class_fullname__: ShiftScaleRotate
        shift_limit: 0.0625
        scale_limit: 0.1
        rotate_limit: 5
        p: 0.3
      - __class_fullname__: Normalize
        normalization: standard
        mean: [ 0.2716, 0.33, 0.3881, 0.2688 ]
        std: [ 0.1902, 0.1799, 0.1597, 0.2160 ]
        max_pixel_value: 255
        p: 1
      - __class_fullname__: ToTensorV2
        p: 1
